[package]
name = "light"
version = "0.0.1"
authors = ["Justin Dubs <jtdubs@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
image = "0.21.2"
threadpool = "1.7.1"
log = "0.4"
env_logger = "0.6.1"
